
export const INITIAL_POLICIES: string[] = [
    'Acceptable Encryption Policy',
    'Acceptable Use Policy',
    'Acquisition Assessment Policy',
    'Analog ISDN Line Security Policy',
    'Anti-Virus Guidelines',
    'Automatically Forwarded Email Policy',
    'Bluetooth Baseline Requirements Policy',
    'Clean Desk Policy',
    'Communications Equipment Policy',
    'Data Breach Response Policy',
    'Database Credentials Policy',
    'Dial-In Access Policy',
    'Digital Signature Acceptance Policy',
    'Disaster Recovery Plan Policy',
    'DMZ Lab Security Policy',
    'Email Policy',
    'Email Retention Policy',
    'Employee Internet Use Monitoring and Filtering Policy',
    'End User Encryption Key Protection Policy',
    'Ethics Policy',
    'Extranet Policy',
    'Information Logging Standard',
    'Internet DMZ Equipment Policy',
    'Internet Usage Policy',
    'Lab Anti-Virus Policy',
    'Lab Security Policy',
    'Mobile Device Encryption Policy',
    'Mobile Employee Endpoint Responsibility Policy',
    'Pandemic Response Planning Policy',
    'Password Construction Guidelines',
    'Password Protection Policy',
    'Personal Communication Devices and Voicemail Policy',
    'Remote Access Policy',
    'Remote Access Tools Policy',
    'Remote Access, Mobile Computing, and Storage Policy',
    'Removable Media Policy',
    'Risk Assessment Policy',
    'Router and Switch Security Policy',
    'Security Response Plan Policy',
    'Server Audit Policy',
    'Server Malware Protection Policy',
    'Server Security Policy',
    'Social Engineering Awareness Policy',
    'Software Installation Policy',
    'Technology Equipment Disposal Policy',
    'Virtual Private Network (VPN) Policy',
    'Web Application Security Policy',
    'Wireless Communication Policy',
    'Wireless Communication Standard',
    'Workstation Security for HIPAA Policy'
];
